import database from "../config/database.sqlite.js"

database.exec(`
CREATE TABLE IF NOT EXISTS "TAB_MOTORISTAS"(
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "nome" TEXT NOT NULL,
    "cpf" TEXT NOT NULL UNIQUE,
    "placaVeiculo" TEXT NOT NULL,
    "status" TEXT CHECK( status in ('ATIVO', 'INATIVO')) NOT NULL DEFAULT 'ATIVO'
);

CREATE UNIQUE INDEX "IDX_MOTORISTAS_CPF" ON "TAB_MOTORISTAS"("cpf");

CREATE TABLE IF NOT EXISTS "TAB_ENTREGAS"(
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "descricao" TEXT,
    "origem" TEXT NOT NULL,
    "destino" TEXT NOT NULL,
    "status" TEXT CHECK( status IN ('CRIADA', 'EM_TRANSITO', 'ENTREGUE', 'CANCELADA')) NOT NULL DEFAULT 'CRIADA',
    "id_motorista" INTEGER,

    FOREIGN KEY ("id_motorista") REFERENCES "TAB_MOTORISTAS"("id")
);

CREATE INDEX "IDX_ENTREGAS_ORIGEM" ON "TAB_ENTREGAS"("origem");

CREATE INDEX "IDX_ENTREGAS_DESTINO" ON "TAB_ENTREGAS"("destino");

CREATE TABLE IF NOT EXISTS "TAB_EVENTO_ENTREGA"(
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "id_entrega" INTEGER NOT NULL,
    "data_entrega" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "descricao" TEXT,

    FOREIGN KEY ("id_entrega") REFERENCES "TAB_ENTREGAS"("id") ON DELETE CASCADE
);`)